/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Alertas;


import Clases.Conexion;
import Login.Loggin;
import Login.ModificarDatosUsuario;
import Clases.validar;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author l
 */
public class ConfirmacionCambios extends javax.swing.JFrame {

    public int como = 0;
    Conexion cc = new Conexion();
    Connection cn = cc.conexion();
    validar v = new validar();

    /**
     * Creates new form confirmarCambios
     */
    public ConfirmacionCambios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto_alerta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        texto_alerta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        texto_alerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto_alerta.setText("Confirmar Cambios");
        texto_alerta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Por favor ingrese su contraseña");

        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Checkmark_32px.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete_32px.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(92, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(pass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(texto_alerta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(texto_alerta)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void guardar_cambios_usuarios() {

        if (pass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Asegurate de introducir tu contraseña :)", "¡Campos vacios!", JOptionPane.WARNING_MESSAGE);
            v.cambia_color_rojo(pass);
        } else {
            try {
                ResultSet rs = null;
                PreparedStatement ds = cn.prepareStatement("select pass from Usuarios where User_nam = ?");
                ds.setString(1, Loggin.Usuario.getText());
                rs = ds.executeQuery();
                if (rs.next()) {
                    if (pass.getText().equals(rs.getString(1))) {
                        PreparedStatement sdd = cn.prepareStatement("update Usuarios set Primer_nombre = ?, Segundo_nombre = ?, Ape_Paterno = ?,"
                                + " Ape_Materno = ?, Edad = ?, Sexo = ?, Tel = ?, Email = ? where User_nam = ?");
                        sdd.setString(1, ModificarDatosUsuario.nombre.getText());
                        sdd.setString(2, ModificarDatosUsuario.seg_nombre.getText());
                        sdd.setString(3, ModificarDatosUsuario.a_paterno.getText());
                        sdd.setString(4, ModificarDatosUsuario.a_materno.getText());
                        
                        int EDAD = Integer.parseInt(ModificarDatosUsuario.edad.getText());
                        sdd.setInt(5, EDAD);
                        
                        String p2 = "";
                        String p1 = ModificarDatosUsuario.sexo.getSelectedItem().toString();
                        if (p1.equals("Masculino")) {
                            p2 = "M";} else {
                            if (p1.equals("Femenino")) {
                                p2 = "F";
                            }}
                        sdd.setString(6, p2);
                        sdd.setString(7, ModificarDatosUsuario.tel.getText());
                        sdd.setString(8, ModificarDatosUsuario.email.getText());
                        sdd.setString(9, Loggin.Usuario.getText());
                        sdd.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Datos modificados correctamente", "¡Exito!", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } else {
                        
                        JOptionPane.showMessageDialog(null, "Algo fue mal intentalo de nuevo ", "¡Error!", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Algo fue mal intentalo de nuevo ", "¡Error!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ConfirmacionCambios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     guardar_cambios_usuarios();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseClicked
        pass.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(0, 153, 255)));
    }//GEN-LAST:event_passMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new ConfirmacionCambios().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pass;
    public static javax.swing.JLabel texto_alerta;
    // End of variables declaration//GEN-END:variables
}
