/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Alertas;

import Login.AdministrarCuentas;
import Clases.Conexion;
import Login.SingUp;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author l
 */
public class OpcionesAcceso extends javax.swing.JFrame {
    
    Conexion cc = new Conexion();
   Connection cn = cc.conexion();
    
    /**
     * Creates new form opcionesAcceso
     */
    public OpcionesAcceso() {
        initComponents();
        n_usuario();
        comodin.setText("");
        comodin.setVisible(false);
    }

    public void n_usuario() {
        labelUsuario.setText(AdministrarCuentas.oculto.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        texto_alerta = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        labelUsuario = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        UsuarioIlimitado = new javax.swing.JRadioButton();
        UsuarioAccesoLimitado = new javax.swing.JRadioButton();
        Denegar = new javax.swing.JRadioButton();
        comodin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        texto_alerta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        texto_alerta.setText("Establezca un tipo de acceso para el usuario:");

        aceptar.setBackground(new java.awt.Color(204, 204, 204));
        aceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aceptar.setText("Aceptar");
        aceptar.setFocusPainted(false);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        labelUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(153, 153, 255));
        labelUsuario.setText("jLabel1");

        cancelar.setBackground(new java.awt.Color(204, 204, 204));
        cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setFocusPainted(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        UsuarioIlimitado.setText("Usuario Ilimitado");
        UsuarioIlimitado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuarioIlimitadoMouseClicked(evt);
            }
        });

        UsuarioAccesoLimitado.setText("UsuarioAccesoLimitado");
        UsuarioAccesoLimitado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuarioAccesoLimitadoMouseClicked(evt);
            }
        });

        Denegar.setText("Eliminar ");
        Denegar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DenegarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comodin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(UsuarioIlimitado)
                        .addGap(18, 18, 18)
                        .addComponent(UsuarioAccesoLimitado)
                        .addGap(18, 18, 18)
                        .addComponent(Denegar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(texto_alerta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(labelUsuario)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(texto_alerta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuario)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioIlimitado)
                    .addComponent(UsuarioAccesoLimitado)
                    .addComponent(Denegar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comodin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelar)
                            .addComponent(aceptar))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        if (comodin.getText().equals("")) {
            CamposVacios n = new CamposVacios();
            n.setLocationRelativeTo(null);
            n.setVisible(true);
        } else {
            if (UsuarioIlimitado.isSelected()) {
                try {
                    PreparedStatement ups = cn.prepareStatement("update Usuarios set Access = 2 where User_nam = ?");
                    ups.setString(1, labelUsuario.getText());
                    ups.executeUpdate();
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(OpcionesAcceso.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                if (UsuarioAccesoLimitado.isSelected()) {
                    try {
                        PreparedStatement ups = cn.prepareStatement("update Usuarios set Access = 0 where User_nam = ?");
                        ups.setString(1, labelUsuario.getText());
                        ups.executeUpdate();
                        this.dispose();
                    } catch (SQLException ex) {
                        Logger.getLogger(OpcionesAcceso.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    if (Denegar.isSelected()) {
                    try{
                        PreparedStatement ups = cn.prepareStatement("delete from Usuarios where User_nam = ?");
                        ups.setString(1, labelUsuario.getText());
                        ups.executeUpdate();
                        this.dispose();
                    }catch(SQLException ex){
                        Logger.getLogger(OpcionesAcceso.class.getName()).log(Level.SEVERE,null,ex);
                    }
                }
                }
            }

        }
        AdministrarCuentas.ya_asignados();
        AdministrarCuentas.mostrar_pendientes();
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void UsuarioIlimitadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioIlimitadoMouseClicked
        UsuarioAccesoLimitado.setSelected(false);
        Denegar.setSelected(false);
        comodin.setText("op1");
    }//GEN-LAST:event_UsuarioIlimitadoMouseClicked

    private void UsuarioAccesoLimitadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioAccesoLimitadoMouseClicked
        UsuarioIlimitado.setSelected(false);
        Denegar.setSelected(false);
        comodin.setText("op2");
    }//GEN-LAST:event_UsuarioAccesoLimitadoMouseClicked

    private void DenegarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DenegarMouseClicked
        EliminacionDeAcceso c = new EliminacionDeAcceso();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
        UsuarioIlimitado.setSelected(false);
        UsuarioAccesoLimitado.setSelected(false);
        comodin.setText("op3");
    }//GEN-LAST:event_DenegarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesAcceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Denegar;
    private javax.swing.JRadioButton UsuarioAccesoLimitado;
    private javax.swing.JRadioButton UsuarioIlimitado;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel comodin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel texto_alerta;
    // End of variables declaration//GEN-END:variables
}
