
/*
 * Principal.java
 *
 * @author Miguel
 */
package Formulario;

import Clases.conectar;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrador
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();


                    
        
    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpescritorio = new javax.swing.JDesktopPane();
        MenuDelSistema = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        CerrarSesion = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        MenuVender = new javax.swing.JMenu();
        VenderPorFactura = new javax.swing.JMenuItem();
        VenderPorTicket = new javax.swing.JMenuItem();
        MenuRegistrar = new javax.swing.JMenu();
        Productos = new javax.swing.JMenuItem();
        Cientes = new javax.swing.JMenuItem();
        Provedores = new javax.swing.JMenuItem();
        MenuConsultar = new javax.swing.JMenu();
        ConsultarClientes = new javax.swing.JMenuItem();
        ConsultarProducto = new javax.swing.JMenuItem();
        ConsultarFacturas = new javax.swing.JMenuItem();
        ConsultarTickets = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        ReporteClientes = new javax.swing.JMenuItem();
        ReporteProvedores = new javax.swing.JMenuItem();
        ReporteProductos = new javax.swing.JMenuItem();
        ReporteTickets = new javax.swing.JMenuItem();
        ReporteFacturas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jdpescritorio.setBackground(java.awt.SystemColor.controlShadow);

        MenuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x32-archivos.png"))); // NOI18N
        MenuArchivo.setText("Archivo");
        MenuArchivo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MenuArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuArchivoMouseEntered(evt);
            }
        });
        MenuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuArchivoActionPerformed(evt);
            }
        });

        CerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CerrarSesion.setText("Cerrar Sesion");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        MenuArchivo.add(CerrarSesion);

        Salir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        MenuArchivo.add(Salir);

        MenuDelSistema.add(MenuArchivo);

        MenuVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x32-caja.png"))); // NOI18N
        MenuVender.setText("Vender");
        MenuVender.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MenuVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuVenderMouseEntered(evt);
            }
        });
        MenuVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVenderActionPerformed(evt);
            }
        });

        VenderPorFactura.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        VenderPorFactura.setText("Factura");
        VenderPorFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderPorFacturaActionPerformed(evt);
            }
        });
        MenuVender.add(VenderPorFactura);

        VenderPorTicket.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        VenderPorTicket.setText("Ticket");
        VenderPorTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderPorTicketActionPerformed(evt);
            }
        });
        MenuVender.add(VenderPorTicket);

        MenuDelSistema.add(MenuVender);

        MenuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x32-edit_form.png"))); // NOI18N
        MenuRegistrar.setText("Registrar");
        MenuRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MenuRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuRegistrarMouseEntered(evt);
            }
        });
        MenuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarActionPerformed(evt);
            }
        });

        Productos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Productos.setText("Productos");
        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });
        MenuRegistrar.add(Productos);

        Cientes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Cientes.setText("Clientes");
        Cientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CientesActionPerformed(evt);
            }
        });
        MenuRegistrar.add(Cientes);

        Provedores.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Provedores.setText("Provedores");
        Provedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvedoresActionPerformed(evt);
            }
        });
        MenuRegistrar.add(Provedores);

        MenuDelSistema.add(MenuRegistrar);

        MenuConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x32-buscar.png"))); // NOI18N
        MenuConsultar.setText("Consultar");
        MenuConsultar.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        MenuConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuConsultarMouseEntered(evt);
            }
        });
        MenuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultarActionPerformed(evt);
            }
        });

        ConsultarClientes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConsultarClientes.setText("Clientes");
        ConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarClientesActionPerformed(evt);
            }
        });
        MenuConsultar.add(ConsultarClientes);

        ConsultarProducto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConsultarProducto.setText("Productos");
        ConsultarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarProductoActionPerformed(evt);
            }
        });
        MenuConsultar.add(ConsultarProducto);

        ConsultarFacturas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConsultarFacturas.setText("Facturas");
        ConsultarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarFacturasActionPerformed(evt);
            }
        });
        MenuConsultar.add(ConsultarFacturas);

        ConsultarTickets.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConsultarTickets.setText("Tickets");
        ConsultarTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarTicketsActionPerformed(evt);
            }
        });
        MenuConsultar.add(ConsultarTickets);

        MenuDelSistema.add(MenuConsultar);

        MenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x32-reporte.png"))); // NOI18N
        MenuReportes.setText("Reportes");
        MenuReportes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MenuReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuReportesMouseEntered(evt);
            }
        });

        ReporteClientes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ReporteClientes.setText("Clientes");
        ReporteClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteClientesActionPerformed(evt);
            }
        });
        MenuReportes.add(ReporteClientes);

        ReporteProvedores.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ReporteProvedores.setText("Provedores");
        ReporteProvedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteProvedoresActionPerformed(evt);
            }
        });
        MenuReportes.add(ReporteProvedores);

        ReporteProductos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ReporteProductos.setText("Productos");
        ReporteProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteProductosActionPerformed(evt);
            }
        });
        MenuReportes.add(ReporteProductos);

        ReporteTickets.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ReporteTickets.setText("Tickets");
        ReporteTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteTicketsActionPerformed(evt);
            }
        });
        MenuReportes.add(ReporteTickets);

        ReporteFacturas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ReporteFacturas.setText("Facturas");
        ReporteFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteFacturasActionPerformed(evt);
            }
        });
        MenuReportes.add(ReporteFacturas);

        MenuDelSistema.add(MenuReportes);

        setJMenuBar(MenuDelSistema);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jdpescritorio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jdpescritorio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
private void MenuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuArchivoActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_MenuArchivoActionPerformed

private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
// TODO add your handling code here:
    Login p= new Login();
    p.setVisible(true);
    p.pack();
    p.setLocationRelativeTo(null);
                try{
          Clip Sonido=AudioSystem.getClip();
          Sonido.open(AudioSystem.getAudioInputStream(new File("src\\Sonidos\\sonido_salida.wav")));
          Sonido.start();
          
     }catch(Exception ex){
     System.err.println(ex+" error");}
      
    this.setVisible(false);
}//GEN-LAST:event_CerrarSesionActionPerformed

private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
// TODO add your handling code here:
    close();
}//GEN-LAST:event_SalirActionPerformed

private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
// TODO add your handling code here:
     IngresoProductos ip= new IngresoProductos();
    jdpescritorio.add(ip);
    ip.show();
}//GEN-LAST:event_ProductosActionPerformed

private void MenuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_MenuRegistrarActionPerformed

private void CientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CientesActionPerformed
// TODO add your handling code here:
    IngresoCliente cli= new IngresoCliente();
    jdpescritorio.add(cli);
    cli.show();
}//GEN-LAST:event_CientesActionPerformed

private void MenuVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVenderActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_MenuVenderActionPerformed

private void VenderPorFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderPorFacturaActionPerformed
// TODO add your handling code here:
     Factura fac= new Factura();
    jdpescritorio.add(fac);
    fac.show();
}//GEN-LAST:event_VenderPorFacturaActionPerformed

private void ReporteClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteClientesActionPerformed
// TODO add your handling code here:
    
        try {
            conectar cc= new conectar();
            
            JasperReport reportes=JasperCompileManager.compileReport("src\\Reportes\\reportesClientes.jrxml");
            JasperPrint print=JasperFillManager.fillReport(reportes, null,cc.conexion());
           // JasperViewer.viewReport(print);
            JasperViewer view = new JasperViewer (print, false);
            view.setVisible(true);
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    
    
}//GEN-LAST:event_ReporteClientesActionPerformed

private void ConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarClientesActionPerformed
// TODO add your handling code here:
   ConsultasClientes clientes= new ConsultasClientes();
    jdpescritorio.add(clientes);
    clientes.show();
}//GEN-LAST:event_ConsultarClientesActionPerformed

private void ConsultarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarProductoActionPerformed
// TODO add your handling code here:
    ConsultasProductos productos= new ConsultasProductos();
    jdpescritorio.add(productos);
    productos.show();
}//GEN-LAST:event_ConsultarProductoActionPerformed

private void ConsultarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarFacturasActionPerformed
// TODO add your handling code here:
    ConsultasFacturas Facturas= new  ConsultasFacturas();
    jdpescritorio.add(Facturas);
    Facturas.show();
}//GEN-LAST:event_ConsultarFacturasActionPerformed

private void VenderPorTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderPorTicketActionPerformed
// TODO add your handling code here:
    Ticket bol = new Ticket();
    jdpescritorio.add(bol);
    bol.show();
}//GEN-LAST:event_VenderPorTicketActionPerformed

private void MenuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultarActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_MenuConsultarActionPerformed

private void ConsultarTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarTicketsActionPerformed
// TODO add your handling code here:
     ConsultasTickets Boletas= new  ConsultasTickets();
    jdpescritorio.add(Boletas);
    Boletas.show();
}//GEN-LAST:event_ConsultarTicketsActionPerformed

private void ReporteProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteProductosActionPerformed
// TODO add your handling code here:
           try {
            conectar cc= new conectar();
            
            JasperReport reportes=JasperCompileManager.compileReport("src\\Reportes\\reportesProductos.jrxml");
            JasperPrint print=JasperFillManager.fillReport(reportes, null,cc.conexion());
            //JasperViewer.viewReport(print);
            JasperViewer view = new JasperViewer (print, false);
            view.setVisible(true);
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
}//GEN-LAST:event_ReporteProductosActionPerformed

private void ReporteFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteFacturasActionPerformed
// TODO add your handling code here:
    try {
            conectar cc= new conectar();
            
            JasperReport reportes=JasperCompileManager.compileReport("src\\Reportes\\reportesFacturas.jrxml");
            JasperPrint print=JasperFillManager.fillReport(reportes, null,cc.conexion());
            //JasperViewer.viewReport(print);
            JasperViewer view = new JasperViewer (print, false);
            view.setVisible(true);
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
}//GEN-LAST:event_ReporteFacturasActionPerformed

private void ReporteTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteTicketsActionPerformed
// TODO add your handling code here:
      try {
            conectar cc= new conectar();
            
            JasperReport reportes=JasperCompileManager.compileReport("src\\Reportes\\reportesTickets.jrxml");
            JasperPrint print=JasperFillManager.fillReport(reportes, null,cc.conexion());
            //JasperViewer.viewReport(print);
            JasperViewer view = new JasperViewer (print, false);
            view.setVisible(true);
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
}//GEN-LAST:event_ReporteTicketsActionPerformed

    private void ProvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvedoresActionPerformed
    IngresoProvedor pro= new IngresoProvedor();
    jdpescritorio.add(pro);
    pro.show();        // TODO add your handling code here:
    }//GEN-LAST:event_ProvedoresActionPerformed

    private void ReporteProvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteProvedoresActionPerformed
    try {
            conectar cc= new conectar();
            
            JasperReport reportes=JasperCompileManager.compileReport("src\\Reportes\\reportesProvedores.jrxml");
            JasperPrint print=JasperFillManager.fillReport(reportes, null,cc.conexion());
            //JasperViewer.viewReport(print);
            JasperViewer view = new JasperViewer (print, false);
            view.setVisible(true);
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }      // TODO add your handling code here:
    }//GEN-LAST:event_ReporteProvedoresActionPerformed

    private void close(){
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)      
        
     System.exit(0);   
    }            
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
      close();  
    }//GEN-LAST:event_formWindowClosing

    private void MenuArchivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuArchivoMouseEntered
    sonidomouse();   // TODO add your handling code here:
    }//GEN-LAST:event_MenuArchivoMouseEntered

    private void MenuVenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuVenderMouseEntered
    sonidomouse();  // TODO add your handling code here:
    }//GEN-LAST:event_MenuVenderMouseEntered

    private void MenuRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuRegistrarMouseEntered
    sonidomouse();    // TODO add your handling code here:
    }//GEN-LAST:event_MenuRegistrarMouseEntered

    private void MenuConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuConsultarMouseEntered
    sonidomouse();    // TODO add your handling code here:
    }//GEN-LAST:event_MenuConsultarMouseEntered

    private void MenuReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuReportesMouseEntered
    sonidomouse();    // TODO add your handling code here:
    }//GEN-LAST:event_MenuReportesMouseEntered
    
    private void sonidomouse(){
        try{
          Clip Sonido=AudioSystem.getClip();
          Sonido.open(AudioSystem.getAudioInputStream(new File("src\\Sonidos\\pasar_barra.wav")));
          Sonido.start();
          
     }catch(Exception ex){
         
     System.err.println(ex+" error");
     
     }
    }
    
    private void sonidoclic(){
        try{
          Clip Sonido=AudioSystem.getClip();
          Sonido.open(AudioSystem.getAudioInputStream(new File("src\\Sonidos\\pasar_barra.wav")));
          Sonido.start();
          
     }catch(Exception ex){
         
     System.err.println(ex+" error");
     
     }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CerrarSesion;
    private javax.swing.JMenuItem Cientes;
    private javax.swing.JMenuItem ConsultarClientes;
    private javax.swing.JMenuItem ConsultarFacturas;
    private javax.swing.JMenuItem ConsultarProducto;
    private javax.swing.JMenuItem ConsultarTickets;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuConsultar;
    private javax.swing.JMenuBar MenuDelSistema;
    private javax.swing.JMenu MenuRegistrar;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenu MenuVender;
    private javax.swing.JMenuItem Productos;
    private javax.swing.JMenuItem Provedores;
    private javax.swing.JMenuItem ReporteClientes;
    private javax.swing.JMenuItem ReporteFacturas;
    private javax.swing.JMenuItem ReporteProductos;
    private javax.swing.JMenuItem ReporteProvedores;
    private javax.swing.JMenuItem ReporteTickets;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem VenderPorFactura;
    private javax.swing.JMenuItem VenderPorTicket;
    public static javax.swing.JDesktopPane jdpescritorio;
    // End of variables declaration//GEN-END:variables
}
